name: building auth-service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout required code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            pom.xml
            common-lib
            auth-service
          sparse-checkout-cone-mode: true

      - name: Java setup
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Check Java and Maven
        run: |
          java -version
          mvn -version

      - name: Build auth-service with dependencies
        run: mvn clean package -DskipTests -pl auth-service -am

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: auth-service.jar
          path: auth-service/target/*.jar