name: Build Auth Service

on:
  push:
    branches:
      - main

jobs:
  build-auth-service:
    name: Build auth-service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout required code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            pom.xml
            common-lib
            auth-service
          sparse-checkout-cone-mode: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin
          cache: maven

      - name: Build auth-service
        run: mvn clean package -B -DskipTests -pl auth-service -am

      - name: Upload auth-service JAR
        uses: actions/upload-artifact@v4
        with:
          name: auth-service.jar
          path: auth-service/target/*.jar